### ISSUE TITLE
Webpack error when using this loader

### ISSUE THREAD

**Issue by elado** [webpack-contrib/source-map-loader#11]
Webpack version = 1.12.11

I have a module that compiles itself with `babel -s -d lib/ src/` and generates `.js` and `.js.map` in `lib`.

I get this error whether I use this loader or an inline source map (issue reported here too - https://github.com/webpack/webpack/issues/1895) so I believe this is a webpack issue, but is there a fix this loader can introduce?

```
Error: No element indexed by 1
    at ArraySet_at [as at] (<proj>/node_modules/react-hot-loader/node_modules/source-map/lib/source-map/array-set.js:93:11)
    at SourceMapConsumer.<anonymous> (<proj>/node_modules/react-hot-loader/node_modules/source-map/lib/source-map/source-map-consumer.js:147:69)
    at Array.map (native)
    at SourceMapConsumer_eachMapping [as eachMapping] (<proj>/node_modules/react-hot-loader/node_modules/source-map/lib/source-map/source-map-consumer.js:146:16)
    at Function.SourceNode_fromStringWithSourceMap [as fromStringWithSourceMap] (<proj>/node_modules/react-hot-loader/node_modules/source-map/lib/source-map/source-node.js:84:26)
    at Object.module.exports (<proj>/node_modules/react-hot-loader/index.js:88:16)
 @ ./src/blah.js 11:40-88
```

**Comment by michael-ciniawsky** [comment]
This issues is very old, did you resolve it with a newer version of `webpack`, and does this 'always' happen (without the `react-hot-loader`) ? I'm closing this for now, but feel free to reopen :)
